### ISSUE TITLE
splitting up tasks

### ISSUE THREAD

**Issue by wdelva** [wdelva/RSimpactHelp#3]
Please have a look at the Board on Trello "Letter to the editor on Harling JAIDS 2014".
You will find that we need to calculate a number of summary statistics for each simulation run. Each of these calculations should be performed by a function that will form part of the RSimpactHelper package.

@josevans will build functions for calculating statistics related to the degree distribution.
@wdelva will build functions for calculating HIV incidence
@roxannebeauclair, can you write the functions for calculating the age-mixing metrics and HIV prevalence estimates: median and IQR of age differences; HIV prevalence; ART coverage. We can skype to discuss the details.

**Comment by wdelva** [comment]
@josevans @roxannebeauclair @wdelva We are almost through this issue. What's still outstanding is code to calculate population growth and ART coverage. Seeing that Roxy is not available in the immediate term, I will write these functions. Wim

**Comment by roxannebeauclair** [comment]
Great. After the AIDS conference let me know what is still outstanding and
maybe I can help 😀

On Thursday, July 14, 2016, Wim Delva notifications@github.com wrote:

> We are almost through this issue. What's still outstanding is code to
> calculate population growth and ART coverage. Seeing that Roxy is not
> available in the immediate term, I will write these functions. Wim
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/wdelva/RSimpactHelp/issues/3#issuecomment-232679787,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADi2YVb33UQSIyiZKHGtSCFOb97YvXzUks5qVkXvgaJpZM4I9P7L
> .

## 

Roxanne Beauclair,  PhD Candidate, MA, MPH
International Centre for Reproductive Health (ICRH)
Ghent University, Belgium
www.icrh.org

The South African Department of Science and Technology / National Research
Foundation (DST/NRF)
Centre of Excellence in Epidemiological Modelling and Analysis (SACEMA)
Stellenbosch University, South Africa
www.sacema.com

Tel: +27 21 808 9236 (work)
Cell: +27 82 212 1621 (cell)

**Comment by Josline90** [comment]
Dear all,

Thanks for the great work done.

 I am supposed to push two more scripts;
-    degree.distr.fitter()
-    degree.hist.makwe()

Latest Monday.

Thanks.

Josline.

On 14 July 2016 at 16:34, Roxanne notifications@github.com wrote:

> Great. After the AIDS conference let me know what is still outstanding and
> maybe I can help 😀
> 
> On Thursday, July 14, 2016, Wim Delva notifications@github.com wrote:
> 
> > We are almost through this issue. What's still outstanding is code to
> > calculate population growth and ART coverage. Seeing that Roxy is not
> > available in the immediate term, I will write these functions. Wim
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/wdelva/RSimpactHelp/issues/3#issuecomment-232679787
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/ADi2YVb33UQSIyiZKHGtSCFOb97YvXzUks5qVkXvgaJpZM4I9P7L
> > 
> > .
> 
> ## 
> 
> Roxanne Beauclair, PhD Candidate, MA, MPH
> International Centre for Reproductive Health (ICRH)
> Ghent University, Belgium
> www.icrh.org
> 
> The South African Department of Science and Technology / National Research
> Foundation (DST/NRF)
> Centre of Excellence in Epidemiological Modelling and Analysis (SACEMA)
> Stellenbosch University, South Africa
> www.sacema.com
> 
> Tel: +27 21 808 9236 (work)
> Cell: +27 82 212 1621 (cell)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/wdelva/RSimpactHelp/issues/3#issuecomment-232683351,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiMrveKbXXUjBQZp4JSLJBVpy1CBtIbks5qVkjhgaJpZM4I9P7L
> .

## 

Josline Otieno | Structured Masters Student,AIMS South Africa,Class of 2016,
BSc (Stats), MSc (Mathematical Sciences).
6 Melrose Road,Muizenberg, Cape Town,South Africa,7945.
Mobile:  +27(0) 61 913 7953 <%2B27%280%29%2061%20243%200324> or  +254(0) 70
014 9824.
Emails:josline@aims.ac.za evansotieno@aims.ac.za | brillyjoss@gmail.com

## evaniceotieno09@gmail.com

## Of all the senses,sight must be the most delightful.

**Comment by Josline90** [comment]
- degree.hist.maker()

On 14 July 2016 at 21:20, Josline Adhiambo Otieno josline@aims.ac.za
wrote:

> Dear all,
> 
> Thanks for the great work done.
> 
>  I am supposed to push two more scripts;
> -    degree.distr.fitter()
> -    degree.hist.makwe()
> 
> Latest Monday.
> 
> Thanks.
> 
> Josline.
> 
> On 14 July 2016 at 16:34, Roxanne notifications@github.com wrote:
> 
> > Great. After the AIDS conference let me know what is still outstanding and
> > maybe I can help 😀
> > 
> > On Thursday, July 14, 2016, Wim Delva notifications@github.com wrote:
> > 
> > > We are almost through this issue. What's still outstanding is code to
> > > calculate population growth and ART coverage. Seeing that Roxy is not
> > > available in the immediate term, I will write these functions. Wim
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/wdelva/RSimpactHelp/issues/3#issuecomment-232679787
> > > ,
> > > or mute the thread
> > > <
> > > https://github.com/notifications/unsubscribe/ADi2YVb33UQSIyiZKHGtSCFOb97YvXzUks5qVkXvgaJpZM4I9P7L
> > > 
> > > .
> > 
> > ## 
> > 
> > Roxanne Beauclair, PhD Candidate, MA, MPH
> > International Centre for Reproductive Health (ICRH)
> > Ghent University, Belgium
> > www.icrh.org
> > 
> > The South African Department of Science and Technology / National Research
> > Foundation (DST/NRF)
> > Centre of Excellence in Epidemiological Modelling and Analysis (SACEMA)
> > Stellenbosch University, South Africa
> > www.sacema.com
> > 
> > Tel: +27 21 808 9236 (work)
> > Cell: +27 82 212 1621 (cell)
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/wdelva/RSimpactHelp/issues/3#issuecomment-232683351,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ASiMrveKbXXUjBQZp4JSLJBVpy1CBtIbks5qVkjhgaJpZM4I9P7L
> > .
> 
> ## 
> 
> Josline Otieno | Structured Masters Student,AIMS South Africa,Class of
> 2016,
> BSc (Stats), MSc (Mathematical Sciences).
> 6 Melrose Road,Muizenberg, Cape Town,South Africa,7945.
> Mobile:  +27(0) 61 913 7953 <%2B27%280%29%2061%20243%200324> or  +254(0)
> 70 014 9824.
> Emails:josline@aims.ac.za evansotieno@aims.ac.za | brillyjoss@gmail.com
> 
> ## evaniceotieno09@gmail.com
> 
> ## Of all the senses,sight must be the most delightful.

## 

Josline Otieno | Structured Masters Student,AIMS South Africa,Class of 2016,
BSc (Stats), MSc (Mathematical Sciences).
6 Melrose Road,Muizenberg, Cape Town,South Africa,7945.
Mobile:  +27(0) 61 913 7953 <%2B27%280%29%2061%20243%200324> or  +254(0) 70
014 9824.
Emails:josline@aims.ac.za evansotieno@aims.ac.za | brillyjoss@gmail.com

## evaniceotieno09@gmail.com

## Of all the senses,sight must be the most delightful.

**Comment by wdelva** [comment]
I am now starting a new branch called "CoxPH" in which I will write code to (1) create an appropriate dataset for a CoxPH regression, (2) run the CoxPH regression model. The central thing to do, is to "simulate" an annual HIV testing event, so that for each person, their HIV status is recorded annually, as well as the age-difference with their last sexual partner. For people who are in more than 1 relationship at the time of the survey, we will define as "last", the relationship that started most recently.

Note: While Harling et al. used a CoxPH model on the time-scale, with age as a time-varying variable (actually, they may have not even done that, and just included age as a covariate, which would be wrong), I think the better and more correct way to do this analysis, is to do it on an age-scale (so that the baseline hazard function h0(a) is some non-parametric function of age, and that we can, if we wanted to, add time as a covariate. However, in their analysis (and probably in ours), things will be fairly constant over the time period of the analysis, and we won't really need to include this variable.

The Harling CoxPH models look at the hazard of HIV infection at the level of the individual (~do young HIV-negative women with recent partners that were older than them have a higher risk of seroconverting in the near future?). We will replicate this analysis (only in a more correct fashion).
Importantly, however, we will also conduct a relationship-level analysis (~do relationships of young HIV-negative women in which the male partner is older have a higher probability of resulting in a seroconversion in the near future?). This "lower level" analysis will be important in explaining our results.
